### ISSUE TITLE
Group permissions for lokalization projects

### ISSUE THREAD

**Issue by danielbecker** [agentejo/Lokalize#1]
Hi,

This might not be the right place, but I'm not sure how else to get in touch.
I have installed and enabled the Lokalize plugin in out Cockpit installation and it's working great! What I cannot figure out is how to grant permissions to groups so that they can edit language keys. Can this be done? Is so, how would I need to go about this?

Thanks a lot,
Daniel

**Comment by aheinze** [comment]
Hi! Sorry group permissions aren't supported (yet).
